### ISSUE TITLE
Show suggested search terms in search bar

### ISSUE THREAD

**Issue by casruger** [tilburgsciencehub/website#368] opened 2022-04-26 12:14 UTC
At the moment, when someone presses on the search bar to type their search query nothing happens. 
We would like it to be that, if someone clicks on the search bar a menu expands underneath it showing the five most popular information pages. We would like it to show the page title, and when the visitor presses on that title it takes them to the information page. If they start typing, however, these five pages should disappear and the suggested search terms like the appear now should take over. 
The search bar of DataCamp is a good example:
https://www.datacamp.com/
![image](https://user-images.githubusercontent.com/51459017/165297505-6de89b16-1ef0-4081-bd9f-e71a312cb321.png)

We would like to show the 5 most popular information pages (so not the landing pages like /building-blocks, 
but building-blocks/configure-your-computer/statistics-and-computation/latex/) 

As you know we have Google Analytics so maybe you can retrieve these 5 pages via their API.

**Comment by heyarviind** [comment] 2022-11-29 06:27
@hannesdatta @hannesdatta 

Can you please generate an API key so that I can start calling GA API for the same?

You can generate one here https://console.cloud.google.com/

**Comment by hannesdatta** [comment] 2022-11-29 08:49
I've replied to your email w/ the key - pls check whether it works as intended.

**Comment by hannesdatta** [comment] 2022-11-29 11:51
Makes a lot of sense. Thanks. We don't have a dedicated server but host everything fully on Netlify. Can you explore the Netlify documentation what's possible/

**Comment by heyarviind** [comment] 2023-01-09 16:23
I have added the script, will test it once it get merged https://github.com/tilburgsciencehub/website/pull/598

**Comment by heyarviind** [comment] 2023-01-15 16:34
@casruger I have created the pull request, this will show the popular results in the search options https://github.com/tilburgsciencehub/website/pull/599

![Screenshot 2023-01-15 at 10 03 48 PM](https://user-images.githubusercontent.com/21043614/212553611-8bf95343-d87c-4c16-8a95-f578748409a6.png)

**Comment by heyarviind** [comment] 2023-02-11 04:44
this issue has been fixed and can be closed, please see the action logs for confirmation

https://github.com/tilburgsciencehub/website/actions/runs/4149773476/jobs/7178964984

**Closed** 2023-02-11 16:14 UTC
