### ISSUE TITLE
margins ugly

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#154] opened 2021-04-13 10:54 UTC
**Describe the bug**
The margins between `####` look ugly.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/16557730/114541723-5f4e8000-9c57-11eb-84e8-3992d6f16f6c.png">

**To Reproduce**
- browse through the page
 
**Expected behavior**
More margins

**Comment by andreantonacci** [comment] 2021-04-13 11:09
@hannesdatta I can't reproduce your screenshot.

From the published website:
![image](https://user-images.githubusercontent.com/50109671/114543402-71c9b900-9c59-11eb-8fe5-e19cbd5f4d54.png)

Moving up the paragraph and leaving the ### heading below the video, run locally:
![image](https://user-images.githubusercontent.com/50109671/114543451-8443f280-9c59-11eb-97f7-1aa8d8f3887e.png)

**Comment by andreantonacci** [comment] 2021-04-23 08:25
fixed with 451d503

**Closed by andreantonacci** 2021-04-23 08:25 UTC
Labels: bug
