### ISSUE TITLE
Homepage white boxes margins

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/website#151] opened 2021-04-12 17:17 UTC
**Describe the bug**
These white boxes have no space below them anymore. They used to, but now I don't know what happened, I'm pretty sure there was some space before. The left one should definitely not touch the white curve below it.

![image](https://user-images.githubusercontent.com/50109671/114434328-2a90e900-9bc3-11eb-9e1c-56d067f4ca76.png)

InVision:
![image](https://user-images.githubusercontent.com/50109671/114434748-a428d700-9bc3-11eb-8b83-036e241d5c13.png)

**Comment by andreantonacci** [comment] 2021-04-16 10:18
Arvind, I don't know if I'm having a cache issue, but I still see this issue from mobile. It's gone from desktop instead. I don't think it's a cache problem because I see the updated icons from #110 for instance

![IMG_2C3F2AB76213-1](https://user-images.githubusercontent.com/50109671/115010458-be0d3700-9ead-11eb-8968-bbbe87cca8da.jpeg)

**Comment by heyarviind** [comment] 2021-04-16 10:25
the problem is with smaller screen sizes, I have added the margin, it is fixed now.

https://github.com/tilburgsciencehub/website/pull/160

**Comment by andreantonacci** [comment] 2021-04-16 10:53
Reopening because the margin above the curve line is fixed, but now there's less margin BELOW the curve (between the curve and the magnifying glass + "Catch mistakes early". 

Currently it looks too close:

![PixelSnap 2021-04-16 at 12 52 29](https://user-images.githubusercontent.com/50109671/115014510-b308d580-9eb2-11eb-989c-d1201c39beee.png)

From InVision (and similar to what it looked before):

![PixelSnap 2021-04-16 at 12 50 38](https://user-images.githubusercontent.com/50109671/115014520-ba2fe380-9eb2-11eb-8c28-291f08e0f920.png)

**Closed** 2021-04-21 09:52 UTC
Labels: bug
